### ISSUE TITLE
OpenAI API returned status code 404

### ISSUE THREAD

**Issue by rsoesemann** [callawaycloud/llm-apex-agents#7]
I am playing with this incredible piece of art that you have built and struggle with the basics: :-( Where to put the API KEY 
![Screenshot_2023-04-21_at_16_17_19](https://user-images.githubusercontent.com/8180281/233660375-3cbf699b-82da-4491-aa28-7bc2119185e8.png)

**Comment by ChuckJonas** [comment]
That looks right... I noticed that it disappears as well for some reason. I think that's just Salesforce way of hiding it.  Don't forget to assing yourself to the permission set... 

To test, run the OpenAI chat model in anonymous apex. 
```java
OpenAIChatModel chatLLM = new OpenAIChatModel();
ChatModel.Message[] messages = new List<ChatModel.Message>{};
messages.add(new ChatModel.Message('user', 'hello'));
System.debug(chatLLM.chat(messages));
```

 If that doesn't work... Maybe just hard code the key in your class to make sure it's valid.
